services:
  db:
    image: mysql:8.0
    restart: always
    container_name: "mysql-db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: project4
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
